### ISSUE TITLE
[biocterm] [dev] [WIP] biocterm.tmux plugin development

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/biocterm_tmux_plugin#2]
# [biocterm] [dev] [WIP] biocterm.tmux plugin development

#GOAL: 
-To write a tmux plugin designed to work with biocterm that takes the following features from third party plugins, (to avoid bloat, mainly)- with some features auto running upon tmux launch instead of being keybinded. 

tmux-logging <- start_logging.sh, save_complete_history.sh, maybe toggle_logging.sh
^ensure output log makes sense in our file directory and is configured for biocterm

tmux sensible 
tmux continuum 
tmux resurrect 
^ these three should autorun anyways but I will need to double check 

# Tasks 
- [ ] create output log 
https://github.com/tmux-plugins/tmux-logging

- [ ] session loading/restoration and lesson progress log + metadata
https://github.com/tmux-plugins/tmux-continuum
https://github.com/tmux-plugins/tmux-resurrect

- [ ] config pointers + file structure for contained installation
https://github.com/tmux-plugins/tpm/blob/master/docs/changing_plugins_install_dir.md

- [ ] bash scripting for: install, pulling system data, .ini files

- [ ] Look into python Integration

# Resources

tmux plugin manager: https://github.com/tmux-plugins/tpm

[other usability] 
https://github.com/tmux-plugins/tmux-pain-control
https://github.com/tmux-plugins/tmux-yank

---
# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
